=== w3raza/TI/lab02/file.dtd
<!ELEMENT library ( division*)  >
<!ELEMENT division (div_name, book+) >
<!ELEMENT book (author, title, author?, price) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT author (last_name, name)>
<!ELEMENT name (#PCDATA) >
<!ELEMENT div_name (#PCDATA) >
<!ELEMENT last_name (#PCDATA) >
<!ELEMENT price (#PCDATA)>

=== w3raza/TI/lab02/index.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="style.css"?>
<!DOCTYPE library SYSTEM "file.dtd">
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
   <division>
       <div_name>Rozwoj osobisty</div_name>
       <book>
           <author>
               <last_name>Tracy</last_name>
               <name>Brian</name>
            </author>
           <title>Nie tłumacz się działaj!</title>
           <price>22.74</price>
       </book>
       <book>
           <author>
               <last_name>Ericsson</last_name>
               <name>Anders</name>
            </author>
            <author>
               <last_name>Pool</last_name>
               <name>Robert</name>
            </author>
            <title>Droga na szczyt</title>
            <price>26.77</price>
        </book>
        <book>
            <author>
                <last_name>Clear</last_name>
                <name>James</name>
             </author>
            <title>Atomowe nawyki</title>
            <price>27.78</price>
        </book>
    </division>
    <division>
        <div_name>Biografia</div_name>
        <book>
            <author>
                <last_name>Frankl</last_name>
                <name>Viktor</name>
            </author>
            <title>Człowiek w poszukiwaniu sensu</title>
            <price>20.15</price>
        </book>
    </division> 
    <division>
        <div_name>Fantasy</div_name>
        <book>
            <author>
                <last_name>Głuchowski</last_name>
                <name>Dmitrij</name>
            </author>
            <title>FUTU.RE</title>
            <price>26.08</price>
        </book>
        <book>
            <author>
                <last_name>Huxley</last_name>
                <name>Aldous</name>
            </author>
            <title>Nowy wspaniały świat</title>
            <price>20.18</price>
        </book>
    </division> 
</library>
